# Generated by Django 3.2.3 on 2021-12-11 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine_Refill',
            fields=[
                ('refill_id', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True, verbose_name='Refill ID')),
                ('refill_date', models.DateTimeField(verbose_name='Refill Date')),
                ('previous_balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Previous Balance')),
                ('amount_refilled', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount Refilled')),
                ('machine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atm.machine')),
            ],
            options={
                'verbose_name': 'machine refill',
                'verbose_name_plural': 'machines refill',
                'db_table': 'machineRefill',
                'ordering': ['refill_id'],
            },
        ),
    ]
