# Generated by Django 3.2.3 on 2021-12-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atm', '0002_machine_refill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('acc_num', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Account Number')),
                ('name', models.CharField(max_length=100, verbose_name='NAME')),
                ('phone_num', models.BigIntegerField(verbose_name='Phone NUMBER')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Balance')),
            ],
            options={
                'verbose_name': 'account',
                'verbose_name_plural': 'accounts',
                'db_table': 'account',
                'ordering': ['acc_num'],
            },
        ),
    ]
