# Generated by Django 3.2.3 on 2021-12-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atm', '0004_atm_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atm_card',
            name='card_status',
            field=models.BooleanField(default=False, verbose_name='CARD STATUS'),
        ),
        migrations.AlterField(
            model_name='atm_card',
            name='phone_num',
            field=models.BigIntegerField(unique=True, verbose_name='PHONE NUMBER FOR AUTHENTICATION'),
        ),
    ]
