# Generated by Django 3.2.3 on 2021-12-12 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atm', '0007_phone_change'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pin_Change',
            fields=[
                ('tid', models.IntegerField(primary_key=True, serialize=False, verbose_name='TRANSACTION ID')),
                ('date_time', models.DateTimeField(verbose_name='DATE TIME OF TRANSACTION')),
                ('status', models.CharField(max_length=100, verbose_name='STATUS')),
                ('rescode', models.IntegerField(verbose_name='RESPONSE CODE')),
                ('type_trans', models.CharField(max_length=100, verbose_name='TRANSACTION TYPE')),
                ('prev_pin', models.IntegerField(verbose_name='PREVIOUS PIN')),
                ('new_pin', models.IntegerField(verbose_name='NEW PIN')),
                ('atmcard_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atm.atm_card')),
                ('machine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atm.machine')),
            ],
            options={
                'verbose_name': 'pin change',
                'verbose_name_plural': 'pin changes',
                'db_table': 'pinChange',
                'ordering': ['tid'],
            },
        ),
    ]
