# Generated by Django 3.2.3 on 2021-12-12 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atm', '0008_pin_change'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cash_Transfer',
            fields=[
                ('tid', models.IntegerField(primary_key=True, serialize=False, verbose_name='TRANSACTION ID')),
                ('date_time', models.DateTimeField(verbose_name='DATE TIME OF TRANSACTION')),
                ('status', models.CharField(max_length=100, verbose_name='STATUS')),
                ('rescode', models.IntegerField(verbose_name='RESPONSE CODE')),
                ('type_trans', models.CharField(max_length=100, verbose_name='TRANSACTION TYPE')),
                ('ben_acc_num', models.BigIntegerField(verbose_name='BENEFICIARY ACCOUNT NUMBER')),
                ('ben_name', models.CharField(max_length=100, verbose_name='BENEFICIARY NAME')),
                ('amt_trans', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='AMOUNT')),
                ('atmcard_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atm.atm_card')),
                ('machine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atm.machine')),
            ],
            options={
                'verbose_name': 'cash transfer',
                'verbose_name_plural': 'cash transfers',
                'db_table': 'cashTransfer',
                'ordering': ['tid'],
            },
        ),
    ]
