# Generated by Django 3.2.3 on 2021-12-12 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atm', '0009_cash_transfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('tid', models.IntegerField(primary_key=True, serialize=False, verbose_name='TRANSACTION ID')),
                ('date_time', models.DateTimeField(verbose_name='DATE TIME OF TRANSACTION')),
                ('status', models.CharField(max_length=100, verbose_name='STATUS')),
                ('rescode', models.IntegerField(verbose_name='RESPONSE CODE')),
                ('type_trans', models.CharField(max_length=100, verbose_name='TRANSACTION TYPE')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='AMOUNT PAID')),
                ('service', models.CharField(max_length=100, verbose_name='SERVICE DETAILS')),
                ('atmcard_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atm.atm_card')),
                ('machine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atm.machine')),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
                'db_table': 'services',
                'ordering': ['tid'],
            },
        ),
        migrations.CreateModel(
            name='Cash_Withdrawal',
            fields=[
                ('tid', models.IntegerField(primary_key=True, serialize=False, verbose_name='TRANSACTION ID')),
                ('date_time', models.DateTimeField(verbose_name='DATE TIME OF TRANSACTION')),
                ('status', models.CharField(max_length=100, verbose_name='STATUS')),
                ('rescode', models.IntegerField(verbose_name='RESPONSE CODE')),
                ('type_trans', models.CharField(max_length=100, verbose_name='TRANSACTION TYPE')),
                ('amt_with', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='AMOUNT WITHDRAWN')),
                ('cur_bal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='CURRENT BALANCE')),
                ('atmcard_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atm.atm_card')),
                ('machine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atm.machine')),
            ],
            options={
                'verbose_name': 'cash withdrawal',
                'verbose_name_plural': 'cash withdrawals',
                'db_table': 'cashWithdrawal',
                'ordering': ['tid'],
            },
        ),
    ]
